version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    user: "mongodb:mongodb"
    command: mongod --bind_ip_all
    volumes:
      - mongodbdata:/data/db
  postgres:
    image: postgres:latest
    ports:
      - "10000:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresdata:/data
volumes:
  mongodbdata:
  postgresdata: